# https://taskfile.dev

version: '3'

vars:
  ACR_NAME: geoanalytics
  IMAGE_NAME: geoanalytics/services/webmap
  IMAGE_TAG: 0.0.1

tasks:
  
  build.stream1:
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image {{.IMAGE_NAME}}/stream1:{{.IMAGE_TAG}} --file Containerfile.stream1 .

  build.stream2:
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image {{.IMAGE_NAME}}/stream2:{{.IMAGE_TAG}} --file Containerfile.stream2 .
